build: create docker images as part of the release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,12 +3,12 @@
 name: release
 
 on:  # yamllint disable-line rule:truthy
-  # push:
-  #   tags:
-  #     - "[0-9]+.[0-9]+.[0-9]+"
-  #     - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
-  #     - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
-  #     - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
+  push:
+    tags:
+      - "[0-9]+.[0-9]+.[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
   pull_request:
     branches:
       - main
@@ -18,141 +18,135 @@ env:
   OWNER: "bolajiwahab"
 
 jobs:
-  # details:
-  #   # if: github.ref == 'refs/heads/main'
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     new_version: ${{ steps.release.outputs.new_version }}
-  #     suffix: ${{ steps.release.outputs.suffix }}
-  #     tag_name: ${{ steps.release.outputs.tag_name }}
-  #   steps:
-  #     - uses: actions/checkout@v2
+  details:
+    runs-on: ubuntu-latest
+    outputs:
+      new_version: ${{ steps.release.outputs.new_version }}
+      suffix: ${{ steps.release.outputs.suffix }}
+      tag_name: ${{ steps.release.outputs.tag_name }}
+    steps:
+      - uses: actions/checkout@v4
 
-  #     - name: Extract tag and Details
-  #       id: release
-  #       run: |
-  #         if [ "${{ github.ref_type }}" = "tag" ]; then
-  #           TAG_NAME=${GITHUB_REF#refs/tags/}
-  #           NEW_VERSION=$(echo $TAG_NAME | awk -F'-' '{print $1}')
-  #           SUFFIX=$(echo $TAG_NAME | grep -oP '[a-z]+[0-9]+' || echo "")
-  #           echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
-  #           echo "suffix=$SUFFIX" >> "$GITHUB_OUTPUT"
-  #           echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
-  #           echo "Version is $NEW_VERSION"
-  #           echo "Suffix is $SUFFIX"
-  #           echo "Tag name is $TAG_NAME"
-  #         else
-  #           echo "No tag found"
-  #           exit 1
-  #         fi
+      - name: Extract tag and Details
+        id: release
+        run: |
+          if [ "${{ github.ref_type }}" = "tag" ]; then
+            TAG_NAME=${GITHUB_REF#refs/tags/}
+            NEW_VERSION=$(echo $TAG_NAME | awk -F'-' '{print $1}')
+            SUFFIX=$(echo $TAG_NAME | grep -oP '[a-z]+[0-9]+' || echo "")
+            echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
+            echo "suffix=$SUFFIX" >> "$GITHUB_OUTPUT"
+            echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
+            echo "Version is $NEW_VERSION"
+            echo "Suffix is $SUFFIX"
+            echo "Tag name is $TAG_NAME"
+          else
+            echo "No tag found"
+            exit 1
+          fi
 
-  # check_pypi:
-  #   # if: github.ref == 'refs/heads/main'
-  #   needs: details
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Fetch information from PyPI
-  #       run: |
-  #         response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
-  #         latest_previous_version=$(echo $response | jq --raw-output "select(.releases != null) | .releases | keys_unsorted | last")
-  #         if [ -z "$latest_previous_version" ]; then
-  #           echo "Package not found on PyPI."
-  #           latest_previous_version="0.0.0"
-  #         fi
-  #         echo "Latest version on PyPI: $latest_previous_version"
-  #         echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV
+  check_pypi:
+    needs: details
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fetch information from PyPI
+        run: |
+          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
+          latest_previous_version=$(echo $response | jq --raw-output "select(.releases != null) | .releases | keys_unsorted | last")
+          if [ -z "$latest_previous_version" ]; then
+            echo "Package not found on PyPI."
+            latest_previous_version="0.0.0"
+          fi
+          echo "Latest version on PyPI: $latest_previous_version"
+          echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV
 
-  #     - name: Compare versions and exit if not newer
-  #       run: |
-  #         NEW_VERSION=${{ needs.details.outputs.new_version }}
-  #         LATEST_VERSION=$latest_previous_version
-  #         if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
-  #           echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
-  #           exit 1
-  #         else
-  #           echo "The new version $NEW_VERSION is greater than the latest version $LATEST_VERSION on PyPI."
-  #         fi
+      - name: Compare versions and exit if not newer
+        run: |
+          NEW_VERSION=${{ needs.details.outputs.new_version }}
+          LATEST_VERSION=$latest_previous_version
+          if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
+            echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
+            exit 1
+          else
+            echo "The new version $NEW_VERSION is greater than the latest version $LATEST_VERSION on PyPI."
+          fi
 
-  # setup_and_build:
-  #   # if: github.ref == 'refs/heads/main'
-  #   needs: [details, check_pypi]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v2
+  setup_and_build:
+    needs: [details, check_pypi]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
 
-  #     - name: Set up Python
-  #       uses: actions/setup-python@v4
-  #       with:
-  #         python-version: "3.12"
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
 
-  #     - name: Install dependencies
-  #       run: pip install --no-cache-dir --upgrade pip tox
+      - name: Install dependencies
+        run: pip install --no-cache-dir --upgrade pip tox
 
-  #     - name: Build source and wheel distribution
-  #       run: |
-  #         tox -e build-dist
+      - name: Build source and wheel distribution
+        run: |
+          tox -e build-dist
 
-  #     - name: Upload artifacts
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: dist/
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist
+          path: dist/
 
-  # pypi_publish:
-  #   # if: github.ref == 'refs/heads/main'
-  #   name: Upload release to PyPI
-  #   needs: [setup_and_build, details]
-  #   runs-on: ubuntu-latest
-  #   environment:
-  #     name: release
-  #   permissions:
-  #     id-token: write
-  #   steps:
-  #     - name: Download artifacts
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: dist/
+  pypi_publish:
+    name: Upload release to PyPI
+    needs: [setup_and_build, details]
+    runs-on: ubuntu-latest
+    environment:
+      name: release
+    permissions:
+      id-token: write
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+          path: dist/
 
-  #     - name: Publish distribution to PyPI
-  #       uses: pypa/gh-action-pypi-publish@release/v1
+      - name: Publish distribution to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
 
-  # github_release:
-  #   # if: github.ref == 'refs/heads/main'
-  #   name: Create GitHub Release
-  #   needs: [setup_and_build, details]
-  #   runs-on: ubuntu-latest
-  #   permissions:
-  #     contents: write
-  #   steps:
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
+  github_release:
+    name: Create GitHub Release
+    needs: [setup_and_build, details]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-  #     - name: Download artifacts
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: dist/
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+          path: dist/
 
-  #     - name: Create GitHub Release
-  #       id: create_release
-  #       env:
-  #         GH_TOKEN: ${{ github.token }}
-  #       run: |
-  #         gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
+      - name: Create GitHub Release
+        id: create_release
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
 
   docker_image_release:
-    # if: github.ref == 'refs/heads/main'
     name: Create docker image for ${{ matrix.platform }}
-    # needs: [setup_and_build, details]
+    needs: [setup_and_build, details]
     runs-on: ubuntu-latest
     permissions:
       contents: read
       packages: write
-    # environment:
-    #   name: release
+    environment:
+      name: release
     strategy:
       fail-fast: false
       matrix:
@@ -161,27 +155,27 @@ jobs:
           - linux/arm64
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
       - name: Log in to GitHub Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.8.0
+        uses: docker/setup-buildx-action@v3
 
       - name: Build and Push Docker Image
-        uses: docker/build-push-action@v6.11.0
+        uses: docker/build-push-action@v6
         with:
           platforms: ${{ matrix.platform }}
           push: true
           tags: |
-            ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest
+            ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:$${{ needs.details.outputs.tag_name }}
 
-      # - name: Post Image URL
-      #   run: echo "Docker image published at ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:${${{ needs.details.outputs.tag_name }}"
+      - name: Post Image URL
+        run: echo "Docker image published at ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:${${{ needs.details.outputs.tag_name }}"
